### PR TITLE
`dvdrtools` does not work on Linuxbrew

### PR DESCRIPTION
**Pull request by retokromer**
See: https://github.com/amiaopensource/homebrew-amiaos/issues/31

### CODE REVIEW

**Comment by retokromer** [comment]
What part of the `mm` package does use `dvdrtools`?

**Comment by retokromer** [comment]
ping

**Comment by dericed** [comment]
`makedvd` uses `mkisofs` which is part of `dvdrtools`

**Comment by dericed** [comment]
Is there a linuxbrew source for `mkisofs`? Maybe in `cdrtools`.

**Comment by retokromer** [comment]
Thank you for the information! I did search for `dvdrtools`…

When back from Ljubljana, I will check if there is a replacement for `mkisofs` in Linuxbrew.

**Comment by retokromer** [comment]
On Ubuntu 14.04 LTS is works when using `cdrtools`.

**Comment by retokromer** [comment]
Tested on Ubuntu 16.04.2 LTS and Slackware 14.2, as well as on Ubuntu 14.04.5 LTS.

**Comment by retokromer** [comment]
ping

**Comment by dericed** [comment]
LGTM

**Comment by retokromer** [comment]
I have no write access.

**Pull request merged**
