### PR TITLE
installation instructions

### PR DESCRIPTION
**Pull request by retokromer**
- still refers to `dericed/mm`

### CODE REVIEW

**Comment by dericed** [comment]
@retokromer some conflicts after the update

**Comment by retokromer** [comment]
Hmm... Strange, it's just text editing, I'll check later.

**Comment by privatezero** [comment]
Oh weird!  I didn't see this pull request and made the exact same change this morning (minus fixing the typo).  That is probably what is causing the conflict!

**Comment by retokromer** [comment]
OK, I close this. (I saw it because I was trying to find out where the FFmpeg last release vs. HEAD has been coded.)

**Pull request closed without merging**
